### ISSUE TITLE
DNS_STATE_ASKING in locked state

### ISSUE THREAD

**Issue by st0ff3r** [pfalcon/lwip-esp8266#1]
in dns_check_entry() if the dns queue is filled and there is no answer from dns server (state DNS_STATE_ASKING) it will never resend request and therefore is in locked state.

Shouldn't every request timeout eventually even if the reply from dns server is lost?

https://github.com/pfalcon/lwip-esp8266/blob/385a7c3c7dfcc1cabb636baa17b3959d95335270/src/core/dns.c#L661

**Comment by pfalcon** [comment]
Wrong project. You're interested to communicate with lwIP upstream.
